<script src="{{asset('js_2/js/jquery.min.js')}}"></script>
<script src="{{asset('js_2/js/jquery-migrate-3.0.1.min.js')}}"></script>
<script src="{{asset('js_2/js/popper.min.js')}}"></script>
<script src="{{asset('js_2/js/bootstrap.min.js')}}"></script>
<script src="{{asset('js_2/js/jquery.easing.1.3.js')}}"></script>
<script src="{{asset('js_2/js/jquery.waypoints.min.js')}}"></script>
<script src="{{asset('js_2/js/jquery.stellar.min.js')}}"></script>
<script src="{{asset('js_2/js/owl.carousel.min.js')}}"></script>
<script src="{{asset('js_2/js/jquery.magnific-popup.min.js')}}"></script>
<script src="{{asset('js_2/js/aos.js')}}"></script>
<script src="{{asset('js_2/js/jquery.animateNumber.min.js')}}"></script>
<script src="{{asset('js_2/js/bootstrap-datepicker.js')}}"></script>
<script src="{{asset('js_2/js/scrollax.min.js')}}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{{asset('js_2/js/google-map.js')}}"></script>
<script src="{{asset('js_2/js/main.js')}}"></script>